# Generated by Django 2.2.7 on 2019-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20191121_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_bank',
            name='adress_key',
            field=models.TextField(default='India'),
        ),
    ]
